apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app-app-deployment
  labels:
    app: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-pod
      app: lab-app
  template:
    metadata:
      name: app-pod
      labels:
        name: app-pod
        app: lab-app

    spec:
      containers:
      - name: app
        image: registry.nascop.org:5000/lab:1.3
        volumeMounts:
          - mountPath: /var/www/lab
            name: app-data
        ports:
          - containerPort: 9000
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "composer install"]
      volumes:
        - name: app-data
          hostPath:
            path: /var/lib/docker/volumes/lab_myapp/_data/
            type: Directory
      
