apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app-app-deployment
  labels:
    app: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-pod
      app: lab-app
  template:
    metadata:
      name: app-pod
      labels:
        name: app-pod
        app: lab-app

    spec:
      containers:
      - name: app
        image: mwendakith/lab:1
        resources:
          limits:
            cpu: 0.2
            memory: "128Mi"
        volumeMounts:
          - mountPath: /var/www/lab
            name: app-data
        ports:
        - containerPort: 7000
      volumes:
        - name: app-data
          hostPath:
            path: /var/lib/docker/volumes/lab_myapp/_data/
            type: Directory
