apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app-redis-deployment
  labels:
    app: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: lab-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: lab-app

    spec:
      containers:
      - name: redis
        image: redis
        args: ["--appendonly yes"]
        resources:
          limits:
            cpu: 0.2
            memory: "128Mi"
        volumeMounts:
          - mountPath: /data
            name: redis-data
        ports:
        - containerPort: 6379
      volumes:
        - name: redis-data
          hostPath:
            path: /var/lib/docker/volumes/lab_redis_data/_data/
            type: Directory
