apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app-nginxplus-deployment
  labels:
    app: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginxplus-pod
      app: lab-app
  template:
    metadata:
      name: nginxplus-pod
      labels:
        name: nginxplus-pod
        app: lab-app

    spec:
      containers:
      - name: web
        image: registry.nascop.org:5000/mynginx:lab-app-kemri-nairobi
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: default-conf
          - mountPath: /etc/amplify-agent/agent.conf
            subPath: agent.conf
            name: amplify-conf
          - mountPath: /var/www/lab/.env
            subPath: .env
            name: env-conf
          - mountPath: /var/www/lab
            name: nginxplus-data
        ports:
        - containerPort: 80
      volumes:
        - name: nginxplus-data
          hostPath:
            path: /var/lib/docker/volumes/lab_myapp/_data/
            type: Directory
        - name: default-conf
          hostPath:
            path: /var/lib/docker/volumes/lab_nginx_conf/_data/
            type: Directory
        - name: amplify-conf
          configMap:
            name: amplify-conf
        - name: env-conf
          configMap:
            name: env-conf

      imagePullSecrets:
        - name: regsecret
